### ISSUE TITLE
Breakpoint overflows attempt button, making it un-clickable

### ISSUE THREAD

**Issue by Awjin** [Codewars/codewars.com#1214]
Demo of bug:

![demo-bug](https://user-images.githubusercontent.com/3211874/32519070-867ab7a2-c3d9-11e7-8581-35f51b75c97e.gif)

The attempt button overflows onto the next line. And since overflow is hidden, I can't scroll to the button, making it hard to click.

The demo was recorded on a 12in Macbook. At fullscreen (which I assume is a breakpoint), the discuss button appears, overflowing the attempt button.

I work around this by making the window smaller, but with a 12in screen, it helps to keep windows as large as possible :)

Semi-related: Issue #1052

**Comment by Awjin** [comment]
Another data point, this is screen-shotted on a 24" monitor, also with the overflow problem:

<img width="1920" alt="screen shot 2017-11-07 at 17 37 34" src="https://user-images.githubusercontent.com/3211874/32521685-76c295f6-c3e2-11e7-88cc-abd272253507.png">

**Comment by jckuhl** [comment]
I am also incapable of viewing the Attempt button unless I resize my Chrome browser.  At full screen on my Mac, the button is almost unclickable because it's out of view.

**Comment by anter69** [comment]
Same issues: #1246 #1256 #1282 #1307 #1322 #1324 should be merged/closed

**Comment by anter69** [comment]
I can also confirm that I sometimes experience the same issue on my old laptop (resolution: 1024x768). 

On my full HD desktop screen the buttons first resize (to a smaller font size) as I make the window smaller, then the layout switches to mobile view (Win7, Chrome64/IE11/FF52), which sems to be correct.

**Comment by kazk** [comment]
@Awjin thanks for the GIF, it makes the issue really clear.
Thanks @anter69 I'll close other issues.

**Comment by Awjin** [comment]
whoo! catch that bug!

![bug slap](https://media.giphy.com/media/3o6nUPPGvsKSiNqvNC/giphy.gif)

**Comment by kriscard** [comment]
Hi, I still have this issue on my Macbook pro (13")! 
It's very difficult to click on the submit buttons. Hope it will be fixed soon 😁

**Comment by Bitcoinera** [comment]
Hi. I get the same issue with full screen on a quite big Vaio. Yes, I also hope this gets fixed soon

**Comment by Bitcoinera** [comment]
Oh, but inspecting it I realized pressing Ctrl + Enter does the trick too

**Comment by Phenomenan** [comment]
I solved the problem by going to my chrome view tab and zoom out.

**Comment by kazk** [comment]
This should be fixed. I've adjusted few things and can't reproduce anymore, but please let me know if it's not.

This was so weird because the buttons **came back** if you made the window just little bit more wider.

**Comment by johnmarkkarr** [comment]
It still does not work for me on Chrome and Safari. I have not tried other browsers. My laptop is about ten years old so that might have something to do with it. All that needs to be done to fix it is to add "overflow: scroll" to main#shell_content. I made a Chrome extension to do that.

**Comment by kazk** [comment]
What's your screen resolution? I'll look into it if you can provide me some information like https://github.com/Codewars/codewars.com/issues/1735 did.

**Comment by johnmarkkarr** [comment]
That sweet spot in between: 1280 x 800.

**Comment by kazk** [comment]
Hmm, I can't reproduce by simulating 1280x800.

![image](https://user-images.githubusercontent.com/639336/54740709-663e5d80-4b79-11e9-8393-082c9b246318.png)

![image](https://user-images.githubusercontent.com/639336/54740420-976a5e00-4b78-11e9-9d37-d433df6d2108.png)

Can you post a screenshot? Does it look like the OP's or https://github.com/Codewars/codewars.com/issues/1214#issuecomment-342647748?

**Comment by johnmarkkarr** [comment]
![](https://i.imgur.com/137OrWy.png)

**Comment by error256** [comment]
It looks like it depends on whether the button is "Unlock solutions" or "View solutions".

**Comment by kazk** [comment]
@johnmarkkarr it should be fixed now.

**Comment by johnmarkkarr** [comment]
Not quite yet. It is strange, if I zoom up or down it works, I can see the buttons. But at 100%, no zoom, I still can't see the buttons. This could just be a weird edge case.

**Comment by error256** [comment]
It works more often now, but it's still bugged when the Discuss button has 2-digits numbers or when the submit button is Submit final.

**Comment by kazk** [comment]
How is it now? I've tested with "Submit Final" and worked for me.

**Comment by error256** [comment]
The last case left is Unlock Solutions + Discuss with a 3-digit number + Submit Final at the same time.

**Comment by error256** [comment]
> The last case left is Unlock Solutions + Discuss with a 3-digit number + Submit Final at the same time.

It looks like it happens for 2-digit numbers on the Discuss button too, that is, in most popular katas.

**Comment by askerovtamerlan** [comment]
![Screenshot 2019-06-09 at 16 59 28](https://user-images.githubusercontent.com/10166046/59159841-0603eb80-8ad8-11e9-80b3-91279f4f48dd.png)

**Comment by kazk** [comment]
I've created a new issue for those conditions (#1839).

@askerovtamerlan can you post a screenshot and your screen resolution there?

---

If you run into this issue, please comment on #1839 with information like screen resolution and screenshots (unless someone already commented with the same condition).
