### ISSUE TITLE
Buttons at the bottom of trainer page are rendered way too tight

### ISSUE THREAD

**Issue by Bubbler-4** [Codewars/codewars.com#1740]
#### Describe the bug

As the title explains.

#### Expected

![](https://i.imgur.com/2aJzt4f.png)

#### Actual

![](https://i.imgur.com/vQEbCsn.png)

I believe this bug was introduced after fixing #1735. Tried resizing the window, and this problem persists over all range from smallest visible to as wide as 1680px.

#### Contexts

- OS: Windows 8.1
- Browser: Google Chrome
- Browser Version: 72.0.3626.109 (official)

**Comment by kazk** [comment]
This happened to me when I deployed the fix and clearing the CDN cache fixed it. I just cleared it again, can you reload the page and see if it's fixed?

**Comment by Bubbler-4** [comment]
Tried reloading the page and restarting the browser, but it isn't fixed.

**Comment by kazk** [comment]
Can you open developer tools and reload the page with cache disabled?

**Comment by Bubbler-4** [comment]
Now it works as expected.

![](https://i.imgur.com/51uT5St.png)

**Comment by kazk** [comment]
Great, I guess it had local cache?

The main cause of the problem is that the hash appended to the filename doesn't seem to change even when the content changes :/ Codewars is using Rails' asset pipeline and it's all magical. I've been clearing CDN cache and hoping that's enough, but I might need to look into the actual problem now.
