### ISSUE TITLE
Submission Timeouts / Poor messaging

### ISSUE THREAD

**Issue by studentprogrammer** [Codewars/codewars.com#18]
Most of the time I'm getting submission timeouts for the last couple hours although the site status indicates everything is fully operational.

**Comment by msmichellegar** [comment]
I'm getting mostly submission timeouts too.

**Comment by ThomWright** [comment]
Same :(

**Comment by bkaes** [comment]
Same here. I think that an additional message on submission timeouts would be great, something like

> Submission timed out. Please try again.
>
> -----
> This doesn't mean that your code is wrong. Instead, our servers are currently a little bit busy and cannot test your submission. You can check [status.codewars.com](http://status.codewars.com) and [our twitter](https://twitter.com/codewars) for current status information.
>
> 
![loading](https://cloud.githubusercontent.com/assets/6301773/6941942/1ee0cef8-d884-11e4-9427-9453a894595f.png)

That explains the issue to new users and disambiguates submission timeouts from processing timeouts.

**Comment by afonsomatos** [comment]
Same here..

**Comment by jhoffner** [comment]
@afonsomatos is this still happening for you? I just restarted the workers about 20 minutes ago and things should be operating as normal. 

The issue is that the background jobs stop processing items from the queue. I'm looking at upgrading to the latest version to see if that fixes the issue. 

@bkaes good suggestion.

**Comment by jhoffner** [comment]
I've deployed upgraded versions of a few of the background worker components, which should hopefully not cause any regressions and fix the instability issues. The problem is not reproducible in development so all we can do is sit and wait to see if it happens again. 

I've marked this an enhancement due to @bkaes suggestion.

**Comment by afonsomatos** [comment]
@jhoffner It is alright now

**Comment by mdibaiee** [comment]
I use Codewars everyday, and this happens often. I really love Codewars but this problem is pretty annoying.

I'm currently trying to submit a kata, tried about 10 times and I'm getting 'Submission timed out' while status.codewars.com says 'All Systems Operational '.

Thanks.

**Comment by bkaes** [comment]
If I'm not mistaken, any changes on tests in the kata editor (either hidden or example test cases) will trigger a test run. This doesn't bode well if there are currently submission timeouts: the kata editor will stay in the "preparing state" infinitely.

I think this is connected to submission timeouts and not an entirely different issue.

**Comment by ryanthames** [comment]
With the exception of a few lucky submissions, I've been getting nothing but submission timeouts since about 11pm CST last night.

**Comment by foiseworth** [comment]
9/10 of my submissions now result in a timeout. It has got progressively worse over the past two days.

**Comment by msmichellegar** [comment]
I'm getting 9/10 timeouts too, although at least it sometimes lets the code go through.

**Comment by franksloan** [comment]
Yep loads of timeouts from me too

**Comment by franksloan** [comment]
Also, 'unknown errors', having run code in js console all works fine

**Comment by jhoffner** [comment]
I just deployed a new monitoring service that will restart the background process when it runs out of memory. Still investigating why the memory issues are happening in the first place - but this should hopefully be a catch-all to the problem.

**Comment by sordidfellow** [comment]
Getting constant "Submission timed out" when submitting console.log("hi") for a javascript kata.

Tried several katas and the problem persists, but status page still shows everything is fine.

**Comment by bkaes** [comment]
@sordidfellow Try to avoid `#number` in in github comments, that's meant for referencing issues.

**Comment by noisyneuron** [comment]
+1

**Comment by ReversePhoenix** [comment]
I get Submission timeout on every kata I try submit.
Chrome.
WIN 32.

**Comment by j932kdsfl303c** [comment]
Was kicking ass just fine, now getting 'Submission timed out. Please try again.' on http://www.codewars.com/kata/54466996990c921f90000d61/train/javascript

http://status.codewars.com reports that 'All Systems Operational'. In case it matters, Cox internet, consistent 25ms ping to google the whole time.

**Comment by colin-jack** [comment]
I've seen lots and lots of timeouts, even just trying to run tests. It makes the site quite difficult to use.

**Comment by Andbondar** [comment]
I encounter same problem for same kata
http://www.codewars.com/kata/vasya-and-stairs

**Comment by akhayoon** [comment]
I'm all submission timeouts right now.

**Comment by leonstafford** [comment]
+1 for better handling of this. seems one would lose interest of a lot of first time users such as myself

**Comment by jhoffner** [comment]
I've upgraded this to a high priority and will get to it the next time I get a block of "CW bug fix" time.

**Comment by bkaes** [comment]
@jhoffner You probably know that, but you can also [create milestones](https://github.com/Codewars/codewars.com/milestones) and assign issues to them ([example](https://github.com/bkaes/codewars-rules/milestones))

**Comment by jhoffner** [comment]
The messaging has been updated for the server timeouts. The code timeouts message comes from the Code Runner service which I still need to update.

**Comment by bkaes** [comment]
The current message doesn't have any newlines, which makes it kind of hard to read.

**Comment by codybousc** [comment]
Hey all, I just wanted to chime in and say that this is still happening. I just got at least 10 server timeouts in a row. I checked the codewar status page and it looks like everything is up and running.

**Comment by codybousc** [comment]
I should also mentioned that I was using GG Chrome and also tried on Safari.

**Comment by toddmetheny** [comment]
Also encountering this issue.

**Comment by Jakub-CZ** [comment]
[One particular kata (possibly for Java only)](http://www.codewars.com/kata/53d40c1e2f13e331fc000c26/java) timeouts 100% of the time when a syntactically correct solution is submitted. (Syntax errors are cought correctly.)
My own test cases pass in Codewars without any issues, but the author's tests always timeout.

**Comment by abelmaniquis** [comment]
I have been getting this problem on [this kata](http://www.codewars.com/kata/perimeter-of-squares-in-a-rectangle/ruby)

**Comment by g964** [comment]
Always impossible to ru, to validate or to re-publish. Nevertheless the status says that everything is in order.

**Comment by seanwbarry** [comment]
Getting timeouts on every submission for the past 30 minutes.  Not sure if this is the right issue to comment in - also frequently pages don't load when clicked (e.g. permanently see the 'Loading Kata: abc123').

**Comment by DanielTheCritic** [comment]
Continuous timeouts all day. Not just with me but with a lot of other developers I'm communicating with. Haven't been able to submit anything since I joined.

**Comment by bkaestner** [comment]
[Folks on gitter recommend](https://gitter.im/Codewars/codewars.com?at=57b469225a4ad61056826303) http://preview.codewars.com

**Comment by davefogo** [comment]
@bkaestner This solution worked, however when going to check for my solutions for that specific kata its empty. Points were awarded but no record of my solution.

**Comment by ioncrash** [comment]
I've been getting timeouts and 500 errors continuously. Also occasionally:

`Unexpected token { in JSON at position 1239426`

also on http://preview.codewars.com

**Comment by ioncrash** [comment]
Run examples completes immediately, but attempt never works

**Comment by AlexK89** [comment]
I can't submit any of katas. each time I got an error ```The server timed out waiting for the request to be processed. This may be due to high server load. Please try your request again. ```

**Comment by elliott-maguire** [comment]
Been getting timeouts for the past couple hours.

**Comment by zarela** [comment]
I get timeout and I don't have a submit button on my kata
