### ISSUE TITLE
"This kata has already been published ..." message not allowing me to publish kata

### ISSUE THREAD

**Issue by Steffan153** [Codewars/codewars.com#2053]
![image](https://user-images.githubusercontent.com/40404519/76046627-04136f80-5f26-11ea-85bc-6c5b5de7d479.png)

No matter which button I click, it doesn't help me with publishing the kata.

**Comment by kazk** [comment]
Can you elaborate?

This should be shown when you're navigating away from the editor with unsaved changes. The first button cancels the navigation. The second button discards the changes and navigates.

If you clicked the first button, it should stay on the editor page and allow you to republish.

**Comment by Steffan153** [comment]
This appears when I click "Re-publish". When i click the first button, then I click republish and it does the same thing again.

**Comment by kazk** [comment]
> This appears when I click "Re-publish".

That's a bug. I'll look into it.

**Comment by kazk** [comment]
I think I found the cause.
It's showing that after re-publish is complete, so your changes should be applied. I'll deploy the fix soon.

**Comment by Steffan153** [comment]
Yeah, but it doesn't actually publish the changes. The spinner goes on for a bit before it pops up.

**Comment by kazk** [comment]
Can you try again? I was able to fix it locally.

**Comment by kazk** [comment]
I reverted tonight's deploy because I found few more bugs that I didn't catch while testing.

Can you try on preview.codewars.com?

**Comment by Steffan153** [comment]
The popup isn't coming up anymore, but it's not saving my changes. Also, for some reason, 'Ctrl+D' isn't doing what I'm used to it doing...

**Comment by kazk** [comment]
> The popup isn't coming up anymore, but it's still not saving my changes.

That's odd :/ I was able to republish a change last night.

> 'Ctrl+D' isn't doing what I'm used to it doing...

I don't think I changed anything there. What did it do?

**Comment by Steffan153** [comment]
> What did it do?

Delete the line.

This is the one I was trying to edit if you want to try it: https://preview.codewars.com/kata/5706aa48fb30081ebb000c21/edit/python

**Comment by kazk** [comment]
For that kata, I see `URIError: malformed URI sequence` error. That's probably the cause of not updating. I'll check what's going on.

For `Ctrl+D`, does it work on www.codewars.com? I'm pretty sure I haven't changed CodeMirror configuration in a while.

**Comment by kazk** [comment]
This only happens when the code contains invalid URI sequence like (`%`). I'm not sure why yet, but the kata data is originally URI encoded. When the page loads, it uses `decodeURIComponent` to replace the data with decoded version. After republishing, it seems to be called again for fields that's not encoded.

#2056 happens when the page crashes like this case. For this case, it gets fixed when refreshing because the kata data is URI encoded again.

**Comment by Steffan153** [comment]
> For Ctrl+D, does it work on www.codewars.com? I'm pretty sure I haven't changed CodeMirror configuration in a while.

Yes, it works fine there. :/

**Comment by kazk** [comment]
Can you try `App.localStorage.get("editorKeyMap")` in developer console and see if it's different in preview vs www?

**Comment by kazk** [comment]
Republishing should be fixed on preview.

`Ctrl+D` doesn't delete a line for me on www nor preview :/

**Comment by Steffan153** [comment]
preview site gives me `undefined` for `App.localStorage.get("editorKeyMap")`
On www, it's `"sublime"`.

> Republishing should be fixed on preview.

Still not working for me, at least with the video digest. I'll try with my own kata.

**Comment by kazk** [comment]
Looks like I broke something else. The change is not reflected to the editor after republishing.

**Comment by kazk** [comment]
OK, I think I finally fixed it. It was confusing because the error message wasn't shown.

"Video Digest" is failing to republish because the example test case is failing.

**Comment by kazk** [comment]
Publishing is fixed.

Can you try if `Ctrl+D` works?
