### ISSUE TITLE
Following a comment-link does not scroll the page, and comments are not highlighted

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2060]
Following reply links does not scroll the page automatically, and the comment threads are not expanded. The former thing works for original comments, though.

At the same time, no comments are highlighted at all.

Example:
* [Original comment](https://www.codewars.com/kata/554f76dca89983cc400000bb/discuss#5e692481deafbd0014018bf4)
* [A reply to it](https://www.codewars.com/kata/554f76dca89983cc400000bb/discuss#5e692c37cec6be0025d621f8)

**Comment by kazk** [comment]
Fixed

**Comment by FArekkusu** [comment]
Still happens with replies under kata solutions (at least). For example, [here](https://www.codewars.com/kata/reviews/5485d20fd8325e250a00013e/groups/54875241ab4964a4c3000d50#5e6a30d0e5be98001e4e7b06) is a reply to a comment left by user SergeyKhrapin (6th counting from most recent) - the comment thread gets expanded, but the page is not scrolled, and the reply is not highlighted.

**Comment by Blind4Basics** [comment]
I recently observed that links on some comments I have bookmarked doesn't land on the correct message: I get to the top of the page only. Some observations:

* it ___seems___ it's related to the number of messages or threads above the linked one. I had 2 links in the same thread:
  - For some time, using the one targetting the highest message of them sent me to the correct message
  - Using the link to the lowest one sent me systematically to the top of the discourse page instead of that message
  - After some time (and a few new threads in the page, so) the two archived links had the same behavior, landing on the top of the discourse page instead of the targeted message
* it ___seems___ part of the problem is related to caching (using FF, here,if that may matter): when landing on the top of the page, refreshing it (F5) send me to the correct message

**Comment by kazk** [comment]
This seems to fail when the comment is in a collapsed reply. I have a fix that works locally, but this might be also affected by other factors like various timings of different events.

I will let you know when it's deployed.

**Comment by kazk** [comment]
The fix is deployed and it seems to be working so far.

**Comment by Blind4Basics** [comment]
yep :) :+1:
