### ISSUE TITLE
Show solved mark everywhere for kata

### ISSUE THREAD

**Issue by oybek** [codewars/codewars.com#2132]
Very often I browse profiles of other users and look which katas they solved and then try to solve them too. But, in that cases there is not sign that this kata was solved by you and often you open  the kata you've solved before.

Show solved mark everywhere for kata.

**Comment by FArekkusu** [comment]
> I browse profiles of other users

> there is not a sign that this kata was solved by you

Isn't it logical that you're seeing what **the other user** has solved when you're viewing... **their** solved-kata page?

**Comment by oybek** [comment]
of course it is logical, I'm suggesting to add sign that this kata was also solved by you

**Comment by hobovsky** [comment]
You could give a try to my script (#1758). A couple of its features got broken after latest CW update and I still did not fix them, but marking kata as solved works:

![image](https://user-images.githubusercontent.com/23709795/81672082-edb7f180-9449-11ea-98cf-5f43a5f108ae.png)
