### ISSUE TITLE
Cannot change email address

### ISSUE THREAD

**Issue by Muhammadrasul446** [codewars/codewars.com#2267]
**Describe the bug**
In the profile settings, i want to change my email address. The field is editable, it changes when i type, but after updating, email becomes as it was before.

**To Reproduce**
Dunno what's that

**Expected behavior**
Email address should remain changed after pressing Update button.

**Screenshots**

**Browser**

- OS: Debian 10 Buster
- Browser Firefox
- Version 82

**Additional context**

**Comment by kazk** [comment]
What's your Codewars username?

**Comment by Blind4Basics** [comment]
https://www.codewars.com/users/Muhammadrasul446

**Comment by kazk** [comment]
@Muhammadrasul446 Do you see the domain of your new email address in this list? https://github.com/FGRibreau/mailchecker/blob/master/list.txt

If so, those are not allowed and it's possible that the error message is just not showing up.

**Comment by kazk** [comment]
Also, can you check if anything is shown in the developer console?

**Comment by Muhammadrasul446** [comment]
> @Muhammadrasul446 Do you see the domain of your new email address in this list? https://github.com/FGRibreau/mailchecker/blob/master/list.txt
> 
> If so, those are not allowed and it's possible that the error message is just not showing up.

My carrent email domain and domain that I want change to, are the same

**Comment by Muhammadrasul446** [comment]
![image](https://user-images.githubusercontent.com/64916997/99033819-9253f100-259d-11eb-8695-a51357207e17.png)
![image](https://user-images.githubusercontent.com/64916997/99033859-aac40b80-259d-11eb-8cec-5bfee851e169.png)
Console and requests to server seem to work fine.

**Comment by Muhammadrasul446** [comment]
And one more thing - nothing there is changeable. I could change my skill level (juior, mid senior etc) from languages panel. But in account settings, changes are ignored, like email.

**Comment by kazk** [comment]
Can you inspect the response of PUT? Codewars can return 200 on failure for historical reasons.

**Comment by Muhammadrasul446** [comment]
![image](https://user-images.githubusercontent.com/64916997/99036573-d208e180-2579-11eb-9138-9c1df6692004.png)
Some javascript and very very long html inside it.

**Comment by kazk** [comment]
Do you have any extensions enabled? If so, can you try without them?

**Comment by Muhammadrasul446** [comment]
Forgot about the problem. That day, I tried also without extensions, also in incognito mode, also in another browser and device. The problem remains.

**Comment by kazk** [comment]
@Muhammadrasul446 Does the field for Stackoverflow account get populated when you open Account Settings? If so, this weird issue has been reported by few users over the last 2 years. Some of them told me it was fixed after doing something on their end (extensions, incognito/private, deleting cache/cookies, etc.). I'd like to know what's causing this, but I've never been able to reproduce it. I don't see any unusual errors on the backend.

Last week, I had another user email us for the similar issue. They first tried disabling all the extensions, but that didn't fix it. Then they tried Incognito with all extension disabled and it worked.

You seem to have tried everything so I'm out of ideas.

**Comment by Muhammadrasul446** [comment]
@kazk yes, stackoverflow field changes successfully, but... email still doesn't change. Also tried clearing cache and cookies after your message.

**Comment by HoreaConst** [comment]
I have the same issue. I tried to change my email address in the Account Settings but every time I hit update the page scrolls up and I all the field from Information change back as they were. This is my username https://www.codewars.com/users/HoreaConst

**Comment by Usernameisalradytaken** [comment]
i also had this same issue. Email address you guys are trying to update is already in the database(that means someone/or you is already register using that email) so you will be not able to update it.

in my case, i already had that email register that i was trying to update. so i login using that email, then deleted my account and then i update my email and it worked.

**Comment by ilylily** [comment]
looks like this has to do with the browser auto-filling the user's current password into the 'new password' box. that "leave blank" warning isn't kidding
