### ISSUE TITLE
Missing data inside "Other kata authored by X" section under a kata description

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2676]
The bookmarks, collections, and satisfaction rating information is not shown for 3 out of the 4 katas listed in the "Other kata authored by FArekkusu" section [here](https://www.codewars.com/kata/625c70f8a071210030c8e22a).

(Red underlines - missing info, green underlines - all's good.)
![image](https://user-images.githubusercontent.com/31668662/165323815-b50ec00d-78aa-4a41-a22d-debe0931963d.png)

I've looked at the page source, and turns out the whole DOM elements which should contain that information are missing. I've also checked the same section for some other approved/beta katas authored by me or other people, and the same problem didn't arise anywhere, even if the same katas show up.

(Red underlines - missing info that is now present, green underlines - all's still good.)
![image](https://user-images.githubusercontent.com/31668662/165322836-a335e493-3651-4c34-addc-b1af2a9dd6bd.png)

**Browser**

- OS: Windows 10
- Browser: Google Chrome
- Version: 100.0.4896.127 (Official Build) (64-bit)

Normally I use an adblock extension in incognito mode as well (you can see an "Extensions" button in the screenshots because of this), but neither turning it off nor disabling for incognito mode entirely changed anything.

**Comment by FArekkusu** [comment]
For some reason the same problem now arises for other my katas, including the "Restoring from history" one I've used in the 2nd screenshot.

At the same time, everything's fine with the "TCO" kata linked above, even though it was bugged for me too when @error256 responded here.

**Comment by Kacarott** [comment]
I have also noticed similar behaviour, but in particular I noticed that in [this collection](https://www.codewars.com/collections/60bb7493b3a07c0019437a19) *every* kata is missing info.

<img width="226" alt="Screen Shot 2022-05-02 at 9 24 02 711 am" src="https://user-images.githubusercontent.com/43819332/166199056-d4bbeae3-df9c-470b-97de-42519b0fb7cd.png">

**Comment by kazk** [comment]
Probably another caching issue from the recent changes Jake did for the updated theme and the landing. I think the ones missing info are showing the version rendered for users not signed in (Jake changed to hide them unless signed in, but the cache is mixing them up).

**Comment by kazk** [comment]
Should be fixed

**Comment by error256** [comment]
I still see it here: https://www.codewars.com/kata/59e1ee463d09a75a4400003b
![image](https://user-images.githubusercontent.com/5375100/166894840-8baa803e-f3a1-4a00-973d-ebd1d7fcf506.png)

**Comment by kazk** [comment]
Fixed
