### ISSUE TITLE
An submit issue in ruby katas

### ISSUE THREAD

**Issue by myjinxin2015** [Codewars/codewars.com#483]
I begin learning ruby. Sometimes  the kata parameter is nil, Output window will be reported to the wrong, but still can do the final submission. (Actually did not complete all the tests)
![!!](https://files.gitter.im/Codewars/codewars.com/thumb/QQ__20160729164658.png)

**Comment by myjinxin2015** [comment]
![!!](https://files.gitter.im/Codewars/codewars.com/QQ__20160729164658.png)

**Comment by myjinxin2015** [comment]
for example, I can use this code passed some(all?) ruby katas:
```
$ii=0
def ball_probability(balls)
  $ii+=1
  $ii==1 ? 0.09 : nil.reverse
end
```
Only need type the right answer of first testcase(0.09), it will passed this kata

**Comment by jhoffner** [comment]
Try it now. My theory was that this was a cache busting issue as this was fixed a while ago.

**Comment by myjinxin2015** [comment]
No, you didn't fix the problem.
I can give you an example:
https://www.codewars.com/kata/52191f3c35f5ecba960003f3
Use this code:
```
$i=0
class Hash
  def get_value( default, *args )
    $i+=1
    $i==1 ? default : nil.reverse 
  end
end
```

**Comment by jhoffner** [comment]
Thanks for the example, that made it very easy to test and fix. Should be good now.
