### ISSUE TITLE
Browser back button navigation

### ISSUE THREAD

**Issue by koffmoff** [Codewars/codewars.com#728]
I find navigation through the Codewars site would benefit a lot from implementing a back stack and hooking it to the browser's back button. Time and again I find myself clicking back, expecting to return to the previous Codewars page, and instead I find myself on the site I was at before even entering Codewards.

For example:
1. I browse the list of katas.
2. I click one kata title to read through its details.
3. I click back in the browser and expect to return to the kata list. Instead I'm returned to whatever was in my browser's back stack before I came to Codewars.

**Comment by jhoffner** [comment]
Backwards navigation should work fine. Which browser/os are you using?

**Comment by koffmoff** [comment]
Nothing fancy. Windows 10 with Chrome. Tried on two different machines. Here's some more details on a basic scenario:

1. I start a new instance of Chrome. It shows a blank tab.
2. I navigate to codewars.com. It signs me in automatically using cached credentials, cookies or whatever. Anyway, I end up at my home screen.
3. I click on the title of the Kata suggested as "Your Next Challenge..."
4. Spinning red wheel, Kata page loads.
5. I click Back in Chrome.
6. Back to the blank tab. I was hoping to get back to my home page.

**Comment by koffmoff** [comment]
Same result in Edge and IE btw.

**Comment by jhoffner** [comment]
Should be resolved now. Thanks.

**Comment by koffmoff** [comment]
Much better now, thanks. Though it's still buggy. In the use case above (1-6) I now indeed return to my home page when clicking back, though I have to click back *twice*! First time nothing happens. Next time I get back to my home page.
