### ISSUE TITLE
"Code challenge voted" honor points added twice

### ISSUE THREAD

**Issue by kazk** [Codewars/codewars.com#862]
I noticed my leaderboard position suddenly went up and found that my honor points increased by more than `1500`. I looked on `/site-events` and found that the points earned for "Code challenge voted" are counted twice:

![image](https://cloud.githubusercontent.com/assets/639336/24077158/e8138876-0c01-11e7-9886-234ebbce4ad3.png)

I've also checked if this actually changed the total (not a rendering glitch):

```javascript
Array.from(document.querySelectorAll('table tr > td:nth-child(3)'), td => td.textContent)
.reduceRight((a, b) => a - b); //=> 0
// selects the right column, for each row of points including the total and
// subtracts each from the total.
```

---

I experienced some weirdness when voting before: #837

**Comment by kazk** [comment]
---

smile67 reported [similar issue](https://www.codewars.com/topics/ranking-and-honor#58c18a9ce61cd98c600000a1) with "Code challenge rank assessed".

![image](https://cloud.githubusercontent.com/assets/639336/24086121/8a4e52e6-0cc6-11e7-90ac-5d9576807800.png)

**Comment by FA810** [comment]
I got the same issue as well with "Code challenge voted", now one counter is moving while the other is still.

**Comment by jhoffner** [comment]
I've got a fix for this that should be rolling out on next deployment. Going through every user is way too expensive the update will correct itself as each user's points for that category get updated.

**Comment by kazk** [comment]
My honor points is fixed now.

**Comment by brendanvos** [comment]
I've got the issue as well for "Github account added"
1 whole honor!

**Comment by AnikaErceg** [comment]
It seems this issue is back: ![](http://i.imgur.com/2uUz4P1.jpg)

It's just one point, but this didn't happen before.
