### ISSUE TITLE
Black options in select box

### ISSUE THREAD

**Issue by Munto** [Codewars/codewars.com#874]
I can't read options in select boxes, everything is black.

![black_options](https://cloud.githubusercontent.com/assets/388683/24401976/e3dc9696-13b6-11e7-931e-56d92ef9bce1.png)

**Comment by DonaldKellett** [comment]
@Munto What browser are you using?  I'm using Safari and the options display just fine.

**Comment by Munto** [comment]
@DonaldKellett I'm using Firefox 52.0.1

**Comment by tachyonlabs** [comment]
I use Firefox with Windows 10 and also see this behavior, with the Status and Progress drop-down boxes in addition to the Language one.

**Comment by brendanvos** [comment]
Same for me on chrome 56.0.2924.87 on windows 10,

**Comment by kazk** [comment]
@Munto are you on Windows too?

Google Chrome 56.0.2924.87 on macOS works fine. I'm assuming @DonaldKellett is on macOS/OS X too.

![image](https://cloud.githubusercontent.com/assets/639336/24427061/874632b8-13be-11e7-9c7c-f3d0e33bd188.png)

**Comment by kazk** [comment]
Also, when did this start?

**Comment by tachyonlabs** [comment]
I've been seeing that kind of behavior for months. Two other places I see it are with the Estimated Rank drop-down box when creating a new kata and the drop-down box to select a kata's rank when approving it.

**Comment by kazk** [comment]
@tachyonlabs is it always like that?

---

I googled a little and maybe this can be a starting point to fix:

```css
/*
select {
  -webkit-appearance: none;
}
*/

select {
  -webkit-appearance: none;
  -moz-appearance: none; /* Firefox */
  background : none;
}
select::-ms-expand {
  display: none; /* IE, Windows */
}
```

See also [Dealing with the select nightmare (MDN)](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Advanced_styling_for_HTML_forms#Dealing_with_the_select_nightmare) :fearful:

> The `<select>` element is considered an "ugly" widget because it's impossible to style it consistently cross platform.

**Comment by brendanvos** [comment]
I joined codewars in January 2017 and I believe it's been like that since.

**Comment by kazk** [comment]
I just tried using Firefox 51.0.1 on macOS.
Seems like a browser issue, now I don't know why @brendanvos's Chrome 56.0.2924.87 on Windows 10 is also affected :confused:

![image](https://cloud.githubusercontent.com/assets/639336/24434847/e362ab44-13e6-11e7-9581-d1d828d316bc.png)

I need to look into this deeper, but that default dropdown can be removed by

```css
select {
  -moz-appearance: none;
}
```

![image](https://cloud.githubusercontent.com/assets/639336/24434960/65003266-13e7-11e7-84c8-b21f98c69179.png)

**Comment by kazk** [comment]
I updated Firefox to the latest 52.0.2 and got this:

![image](https://cloud.githubusercontent.com/assets/639336/24435180/a4bfd3f6-13e8-11e7-83e7-e64ba6fb0aec.png)

By adding `-moz-appearance: none;`:

![image](https://cloud.githubusercontent.com/assets/639336/24435370/c6d46370-13e9-11e7-912f-f16792390c44.png)

**Comment by kazk** [comment]
On Firefox 52.0.2, I got this

![image](https://cloud.githubusercontent.com/assets/639336/24435666/9233107e-13eb-11e7-89e6-189c60ef0b18.png)

by adding

```css
select:-moz-focusring {
    color: transparent;
    text-shadow: 0 0 0 #000;
}
```

<http://stackoverflow.com/a/35534565>

**Comment by jhoffner** [comment]
This should be fixed now.

**Comment by tachyonlabs** [comment]
I'm still seeing it in both Firefox 52.0.2 and Chrome 57.0.2987.133 under Windows 10. I did shift-reload, too, so it shouldn't just be a some-stuff-still-in-cache issue.

**Comment by jhoffner** [comment]
Hmm, I just flushed the CDN cache so try it now. I set the background color of the option tag which seemed to pick up on my local. However I'm using Firefox 54. 

Odd that this happens in Chrome. I was certain this was a recent Firefox regression since it suddenly started happening and newer versions didn't have the issue. I wonder if there is some sort of system setting with Windows 10 that might be affecting this.

**Comment by brendanvos** [comment]
Still broken for me...
Oddly it now looks correct in my SO's computer which I just reformatted.
Both on Windows 10, newest chrome deployment, 64 bit versions of each.

Cleared the browsing data for good measure too.

**Comment by tachyonlabs** [comment]
I restarted both Chrome and Firefox, on both went to https://www.codewars.com/kata/my-languages and again did shift-reload, and now both are working.

**Comment by brendanvos** [comment]
Hmm... the my-languages page is correct for me, but not https://www.codewars.com/kata/
Even tried restarting my entire PC.
